"""Add user bonus transactions

Revision ID: 63966d5da0e0
Revises: 021
Create Date: 2026-10-04 18:02:13.692393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63966d5da0e0'
down_revision: Union[str, None] = '021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bonus_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bonus_transactions_user_id'), 'user_bonus_transactions', ['user_id'], unique=False)
    op.drop_index('ix_learning_events_created_at', table_name='learning_events')
    op.drop_index('ix_learning_events_user_entity', table_name='learning_events')
    op.drop_index('ix_learning_events_user_event', table_name='learning_events')
    op.drop_index('ix_payment_methods_yookassa_payment_method_id', table_name='payment_methods')
    op.create_unique_constraint(None, 'payment_methods', ['yookassa_payment_method_id'])
    op.drop_index('ix_payments_idempotency_key', table_name='payments')
    op.drop_index('ix_payments_yookassa_payment_id', table_name='payments')
    op.create_unique_constraint(None, 'payments', ['idempotency_key'])
    op.create_unique_constraint(None, 'payments', ['yookassa_payment_id'])
    op.drop_constraint('promo_codes_code_key', 'promo_codes', type_='unique')
    op.drop_index('ix_promo_codes_code', table_name='promo_codes')
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.drop_index('uq_subscription_changes_one_scheduled', table_name='subscription_changes', postgresql_where="((status)::text = 'scheduled'::text)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_subscription_changes_one_scheduled', 'subscription_changes', ['user_id'], unique=True, postgresql_where="((status)::text = 'scheduled'::text)")
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.create_index('ix_promo_codes_code', 'promo_codes', ['code'], unique=False)
    op.create_unique_constraint('promo_codes_code_key', 'promo_codes', ['code'])
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index('ix_payments_yookassa_payment_id', 'payments', ['yookassa_payment_id'], unique=True)
    op.create_index('ix_payments_idempotency_key', 'payments', ['idempotency_key'], unique=True)
    op.drop_constraint(None, 'payment_methods', type_='unique')
    op.create_index('ix_payment_methods_yookassa_payment_method_id', 'payment_methods', ['yookassa_payment_method_id'], unique=True)
    op.create_index('ix_learning_events_user_event', 'learning_events', ['user_id', 'event'], unique=False)
    op.create_index('ix_learning_events_user_entity', 'learning_events', ['user_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_learning_events_created_at', 'learning_events', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_bonus_transactions_user_id'), table_name='user_bonus_transactions')
    op.drop_table('user_bonus_transactions')
    # ### end Alembic commands ###
