import { Radius } from '@/constants/theme';
import { useAppTheme, useGlass } from '@/hooks/use-theme-color';
import { useMemo } from 'react';
import { StyleSheet } from 'react-native';

type ThemeColors = ReturnType<typeof useAppTheme>;
type GlassColors = ReturnType<typeof useGlass>;

function buildTestTakingStyles(theme: ThemeColors, glass: GlassColors) {
  return StyleSheet.create({
  container: { flex: 1 },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: glass.border,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 44,
    overflow: 'hidden',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: Radius.lg,
  },
  backButtonText: { fontSize: 16, fontWeight: '500', color: theme.text },
  questionsNavigation: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    paddingVertical: 8,
    gap: 4,
  },
  progressText: { fontSize: 13, fontWeight: '500', color: theme.neutralSoft, marginBottom: 8 },
  topProgressTrack: {
    height: 2,
    width: '100%',
    backgroundColor: glass.progressTrack,
  },
  topProgressFill: {
    height: '100%',
    borderRadius: 9999,
    backgroundColor: theme.primary,
  },
  questionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  questionNumberBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  questionNumberText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
  },
  answerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    width: '100%',
  },
  answerLetterBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    backgroundColor: glass.backgroundSubtle,
    borderWidth: 1,
    borderColor: glass.borderSubtle,
  },
  answerLetterText: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.neutralSoft,
  },
  answerLetterTextSelected: {
    color: theme.primary,
  },
  glassButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: Radius.lg,
    borderWidth: 1,
    minHeight: 44,
    backgroundColor: glass.backgroundSubtle,
    borderColor: glass.border,
  },
  glassButtonText: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.text,
  },
  nextButtonWrap: {
    flex: 1,
    minHeight: 44,
  },
  finishTestButtonGhost: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    borderWidth: 1,
    borderColor: theme.errorContainer,
    backgroundColor: theme.errorContainer,
  },
  finishTestButtonGhostText: { color: theme.error, fontSize: 13, fontWeight: '500' },
  finishTestButton: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    backgroundColor: theme.primary,
  },
  finishTestButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  scrollView: { flex: 1 },
  scrollViewContent: { paddingBottom: 100 },
  content: { padding: 16 },
  questionContainer: {
    padding: 24,
    borderRadius: Radius.xl,
    backgroundColor: glass.background,
    borderWidth: 1,
    borderColor: glass.border,
  },
  questionTitle: { fontSize: 18, lineHeight: 26, color: theme.text, flex: 1 },
  questionTitleWithoutImage: { marginTop: 0 },
  imageContainer: {
    width: '100%',
    marginBottom: 16,
    padding: 12,
    backgroundColor: glass.backgroundSubtle,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: glass.borderSubtle,
  },
  imagePlaceholder: { fontSize: 12, opacity: 0.6, color: theme.neutralSoft },
  questionImage: { width: '100%', minHeight: 200, maxHeight: 400, borderRadius: Radius.lg },
  divider: {
    height: 1,
    borderBottomWidth: 1,
    borderBottomColor: glass.borderSubtle,
    marginVertical: 16,
  },
  answersContainer: { marginBottom: 16, gap: 10 },
  answerButtonContainer: {
    borderWidth: 1,
    borderColor: glass.borderSubtle,
    backgroundColor: glass.backgroundSubtle,
    borderRadius: Radius.lg,
    marginBottom: 0,
    position: 'relative',
  },
  answerButton: {
    borderWidth: 1,
    borderColor: glass.borderSubtle,
    backgroundColor: glass.backgroundSubtle,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: Radius.lg,
  },
  answerButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 4,
    paddingVertical: 0,
    gap: 8,
    width: '100%',
  },
  answerButtonSelected: {
    borderColor: 'rgba(0, 132, 255, 0.4)',
    backgroundColor: 'rgba(0, 132, 255, 0.1)',
  },
  answerButtonShouldBeSelected: {
    borderColor: 'rgba(77, 139, 49, 0.4)',
    borderStyle: 'dashed',
    backgroundColor: 'rgba(77, 139, 49, 0.1)',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: glass.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: { borderColor: theme.primary, backgroundColor: theme.primary },
  checkboxCorrect: { borderColor: theme.success, backgroundColor: theme.success },
  checkboxIncorrect: { borderColor: theme.error, backgroundColor: theme.error },
  radio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: glass.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioSelected: { borderColor: theme.primary },
  radioCorrect: { borderColor: theme.success },
  radioIncorrect: { borderColor: theme.error },
  radioInner: { width: 12, height: 12, borderRadius: 6, backgroundColor: theme.primary },
  radioInnerCorrect: { backgroundColor: theme.success },
  radioInnerIncorrect: { backgroundColor: theme.error },
  answerText: { flex: 1, fontSize: 15, color: theme.text },
  answerBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    zIndex: 1,
  },
  answerBadgeText: { fontSize: 12, fontWeight: '600', color: '#fff' },
  answerTextSelected: { fontWeight: '600' },
  answerTextCorrect: { color: theme.success, fontWeight: '600' },
  answerTextIncorrect: { color: theme.error, fontWeight: '600' },
  resultMessage: { padding: 12, borderRadius: Radius.lg, marginBottom: 16 },
  resultMessageText: { fontSize: 16, fontWeight: '600', marginBottom: 4, color: theme.text },
  resultScoreText: { fontSize: 13, opacity: 0.7, color: theme.neutralSoft },
  buttonsRow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginBottom: 8 },
  previousButton: {
    borderWidth: 1,
    borderColor: glass.border,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    backgroundColor: glass.backgroundSubtle,
  },
  previousButtonText: { color: theme.text, fontSize: 16, fontWeight: '600' },
  skipButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    borderWidth: 1,
    borderColor: glass.border,
    marginTop: 8,
    width: '100%',
    backgroundColor: glass.backgroundSubtle,
  },
  skipButtonText: { fontSize: 16, fontWeight: '600', color: theme.text },
  nextButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    backgroundColor: theme.primary,
    flex: 1,
  },
  nextButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  resultCard: {
    padding: 20,
    borderRadius: Radius.xl,
    backgroundColor: glass.background,
    borderWidth: 1,
    borderColor: glass.border,
    marginBottom: 24,
  },
  resultTitle: { marginBottom: 16, color: theme.text },
  resultItem: { marginBottom: 12, fontSize: 16, color: theme.text },
  statusBadge: { marginTop: 16, padding: 16, borderRadius: Radius.lg, alignItems: 'center' },
  statusText: { color: '#fff', fontSize: 18, fontWeight: '600' },
  fixedButtonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    paddingBottom: 32,
    borderTopWidth: 1,
    borderTopColor: glass.border,
    backgroundColor: glass.header,
  },
  finishButton: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
    backgroundColor: theme.primary,
  },
  finishButtonText: { color: '#fff', fontSize: 18, fontWeight: '600' },
  resultsTitle: {
    marginBottom: 24,
    fontSize: 28,
    fontWeight: '300',
    textAlign: 'center',
    color: theme.text,
  },
  summaryCard: {
    padding: 20,
    borderRadius: Radius.xl,
    backgroundColor: glass.background,
    borderWidth: 1,
    borderColor: glass.border,
    marginBottom: 32,
  },
  summaryTitle: { marginBottom: 16, fontSize: 18, color: theme.text },
  summaryItem: { marginBottom: 12, fontSize: 16, lineHeight: 24, color: theme.text },
  recBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: Radius.md,
  },
  questionResultCard: {
    padding: 20,
    borderRadius: Radius.xl,
    backgroundColor: glass.backgroundSubtle,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: glass.border,
  },
  questionResultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionResultNumber: { fontSize: 18, fontWeight: '700', color: theme.text },
  questionResultBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  questionResultBadgeText: { fontSize: 14, fontWeight: '600' },
  questionResultText: { fontSize: 16, marginBottom: 16, lineHeight: 24, color: theme.text },
  questionAnswersList: { gap: 10, marginBottom: 12 },
  questionAnswerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: glass.borderSubtle,
    backgroundColor: glass.backgroundSubtle,
  },
  questionAnswerCorrect: {
    borderColor: 'rgba(77, 139, 49, 0.4)',
    backgroundColor: 'rgba(77, 139, 49, 0.1)',
  },
  questionAnswerIncorrect: {
    borderColor: 'rgba(255, 107, 107, 0.4)',
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
  },
  questionAnswerShouldBeSelected: {
    borderColor: 'rgba(77, 139, 49, 0.4)',
    borderStyle: 'dashed',
    backgroundColor: 'rgba(77, 139, 49, 0.05)',
  },
  questionAnswerContent: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 12 },
  questionAnswerCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.primary,
  },
  questionAnswerCheckboxCorrect: { backgroundColor: theme.success },
  questionAnswerCheckboxIncorrect: { backgroundColor: theme.error },
  questionAnswerCheckboxEmpty: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: glass.border,
  },
  questionAnswerText: { flex: 1, fontSize: 15, color: theme.text },
  questionAnswerTextCorrect: { color: theme.success, fontWeight: '600' },
  questionAnswerTextIncorrect: { color: theme.error, fontWeight: '600' },
  questionAnswerTextShouldBeSelected: { color: theme.success, fontWeight: '500' },
  questionScoreText: { fontSize: 14, fontWeight: '600', opacity: 0.7, marginTop: 8, color: theme.neutralSoft },
  accordionContainer: {
    marginBottom: 12,
    borderRadius: Radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: glass.border,
  },
  accordionHeader: {
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: glass.background,
  },
  accordionHeaderContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  accordionHeaderLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  accordionQuestionText: { flex: 1, fontSize: 16, lineHeight: 22, color: theme.text },
  accordionStatusBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, flexShrink: 0 },
  accordionStatusBadgeText: { fontSize: 13, fontWeight: '600' },
  accordionContent: {
    padding: 16,
    paddingTop: 12,
    backgroundColor: glass.backgroundSubtle,
  },
  });
}

export function useTestTakingStyles() {
  const theme = useAppTheme();
  const glass = useGlass();
  return useMemo(() => buildTestTakingStyles(theme, glass), [theme, glass]);
}
